#!/bin/sh
sudo cp X11/usumlauts /usr/share/X11/xkb/symbols/
sudo python X11/update-fragment.py
gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'usumlauts')]"

gzip -kf kbd/us-umlauts.map
sudo cp kbd/us-umlauts.map.gz /usr/share/kbd/keymaps/i386/qwerty/
sudo localectl set-keymap --no-convert us-umlauts

echo "If the keyboard doesn't work now, please restart your computer now."
