#!/bin/sh
if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

cp X11/usumlauts /usr/share/X11/xkb/symbols/
setxkbmap usumlauts
python X11/update-fragment.py

gzip -kf kbd/us-umlauts.map
cp kbd/us-umlauts.map.gz /usr/share/kbd/keymaps/i386/qwerty/
localectl set-keymap --no-convert us-umlauts
