#!/bin/sh

cd X11
cp us-umlauts /usr/share/X11/xkb/symbols/
cd ..
setxkbmap us-umlauts

USER_HOME=$(getent passwd $SUDO_USER | cut -d: -f6)
AUTOSTART_FILE="$USER_HOME/.config/autostart/set-umlauts-layout.desktop"

echo -e "[Desktop Entry]\nType=Application\nExec=setxkbmap us-umlauts" > $AUTOSTART_FILE
chmod +x $AUTOSTART_FILE

cd kbd
gzip -k us-umlauts.map
cp us-umlauts.map.gz /usr/share/kbd/keymaps/i386/qwerty/
cd ..
localectl set-keymap --no-convert us-umlauts
